// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTHks2ek8-JzeGjuGYvDIaaz4-h4cD0WE',
    appId: '1:811444864546:web:8c5f2fb79af9657c322c7b',
    messagingSenderId: '811444864546',
    projectId: 'task-manager-e93f5',
    authDomain: 'task-manager-e93f5.firebaseapp.com',
    storageBucket: 'task-manager-e93f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUXmlXzuSuivapZjXFo4VukjG73iU4Yqg',
    appId: '1:811444864546:android:e610ebc7031842b9322c7b',
    messagingSenderId: '811444864546',
    projectId: 'task-manager-e93f5',
    storageBucket: 'task-manager-e93f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzmv84iyaepXMx13FdgEm9Hb0nCPeyOd4',
    appId: '1:811444864546:ios:34e0daf2e160540a322c7b',
    messagingSenderId: '811444864546',
    projectId: 'task-manager-e93f5',
    storageBucket: 'task-manager-e93f5.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzmv84iyaepXMx13FdgEm9Hb0nCPeyOd4',
    appId: '1:811444864546:ios:34e0daf2e160540a322c7b',
    messagingSenderId: '811444864546',
    projectId: 'task-manager-e93f5',
    storageBucket: 'task-manager-e93f5.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTHks2ek8-JzeGjuGYvDIaaz4-h4cD0WE',
    appId: '1:811444864546:web:446a21bcf4027ecb322c7b',
    messagingSenderId: '811444864546',
    projectId: 'task-manager-e93f5',
    authDomain: 'task-manager-e93f5.firebaseapp.com',
    storageBucket: 'task-manager-e93f5.firebasestorage.app',
  );
}
